#!/bin/env python
from lib.types import *
from lib.music_file import read_music_file

from argparse import ArgumentParser, Namespace
from pathlib import Path
import yaml

from typing import Any, List, Dict, Set, cast
import sys



class ArtistManager :
    def __init__(self) :
        self.byid : Dict[str, Artist]  = {} # by id
        self.names : Dict[str, Artist] = {} # by name

        # This id will not be generated by get_id()
        # If the alphabet changes, may need to tweak this.
        self._unknown_id =  '--unknown--'
        self._unknown = Artist(self._unknown_id, self._unknown_id, self._unknown_id)
        self.byid[self._unknown_id] = self._unknown
        self.names[self._unknown_id] = self._unknown

    def unknown(self) -> Artist :
        """Return the record of the `unknown` entity"""
        return self._unknown

    def add_artist(self, name : str, sort_name : str | None = None) -> Artist :
        """Add an artist of the given name and sort_name.
        If the artist name already exists, simply return the record
        params :
            name : artist's name (required)
            sort_name : string to use to sort. If not given, use the @name

        returns :
            Record of the artist.
        """
        sort_name = sort_name if sort_name else name
        if name in self.names :
            return self.names[name]

        new_id = get_id()
        artist = Artist(name, sort_name, new_id)
        self.byid[new_id] = artist
        self.names[name] = artist

        return artist


    def __iter__(self) :
        return iter(sorted(self.byid.values(), key=lambda v: v.sort_name))

class Curate :
    def __init__(self, directory: str, output) -> None :
        self.directory=Path(directory)
        self.output=output
        self.tracks : List[MusicFile] = []
        self.artists = ArtistManager()
        self.albums : List[Album] = []

        if self.output.closed :
            raise Exception("closed")

    ##########################################################
    def add_album(self, name : str, sort_name : str | None = None) -> Album :
        sort_name = sort_name if sort_name else name
        album = Album(name, sort_name)
        self.albums.append(album)
        return album

    ##########################################################
    def add_track(self, new_data : List[MusicFile]) -> None :
        # This may need to be smarter about dups.
        # Maybe
        self.tracks.extend(new_data)

    ##########################################################
    def launch(self) -> int :
        print(f"Starting on collection {self.directory}")

        self.walk_tree(self.directory)

        self.output_data()

        return 0

    ##########################################################
    def walk_tree(self, dir : Path, prefix : str = '') -> None :
        print(f"{prefix}-- Walking directory {dir}")

        # Run through subdirectories
        for entry in dir.iterdir() :
            if entry.is_dir() :
                print(f"{prefix} - recursing {entry}")
                self.walk_tree(dir / entry, prefix + '  ')


        # For now, only lool at directories that have an index file
        index_path = dir / '_index.yml'
        if not index_path.exists() :
            print(f"{prefix}-- no index. returning")
            return

        index_data : Dict[str, Any] = self.read_index_file(index_path)
        if index_data['type'] == 'single' :
            self.read_singles(dir, index_data, prefix)
        elif index_data['type'] == 'album' :
            self.read_album(dir, index_data, prefix)
        else :
            raise Exception(f"Unknown type '{index_data['type']}' in {dir}")

        print(f"{prefix}-- Finished directory {dir}")

    ##########################################################
    def read_singles(self, dir : Path, index_data : Dict[str, Any], prefix : str) -> None :
        if 'files' not in index_data :
            print(f"{prefix} == No files in index - ignoring")
            return
        template =  { **index_data }
        del template['files']

        seen_files = set()
        for filename,v in index_data['files'].items() :
            full_path = dir / filename
            rel_path = full_path.relative_to(self.directory)
            if full_path.exists() :
                music_obj = read_music_file(full_path, rel_path)
                data = {**(music_obj.tags if music_obj.tags else {}), **template, **v}
                data['filename'] = filename
                self.add_to_artist(music_obj, data)
                seen_files.add(filename)
            else :
                print(f"{prefix} - {filename} does not exist - ignoring")
            
        for f in dir.iterdir() :
            filename = f.parts[-1]
            if self.is_music(f) and filename not in seen_files :
                rel_path = f.relative_to(self.directory)
                music_obj = read_music_file(f, rel_path)
                data = {**(music_obj.tags if music_obj.tags else {}), **template}
                data['filename'] = filename
                self.add_to_artist(music_obj, data)

    ##########################################################
    def add_to_artist(self, music : MusicFile, data : Dict[str, Any]) -> None :
        if 'name' not in data :
            data['name'] = Path(data['filename']).stem
        if 'sort_name' not in data :
            data['sort_name'] = data['name']
        track = Track(music, data['name'], data['sort_name'])
        if 'artist' in data :
            artist = self.artists.add_artist(data['artist'])
        else :
            artist = self.artists.unknown()

        artist.add_music(track)
    
    ##########################################################
    def read_album(self, dir : Path, index_data : Dict[str, Any], prefix : str) -> None :
        if 'tracks' not in index_data :
            print(f"{prefix} == No tracks in index - ignoring")
            return
        if 'sort_name' not in index_data :
            index_data['sort_name'] = index_data['name']

        if 'artist' in index_data :
            artist = self.artists.add_artist(index_data['artist'])
        else :
            artist = self.artists.unknown()

        album = Album(index_data['name'], index_data['sort_name'])
        artist.add_music(album)

        for index, t in enumerate(index_data['tracks']) :
            full_path = dir / t['file']
            rel_path = full_path.relative_to(self.directory)
            if full_path.exists() :
                music_obj = read_music_file(full_path, rel_path)
                album.add_track(music_obj, t['name'], index+1)

    ##########################################################
    def read_index_file(self, file : Path) -> Dict[str, Any] :
        index_data : Dict[str, Any] = {'type' : 'album'}
        with open(file, 'r') as f :
            index_data.update(yaml.safe_load(f))

        if 'type' not in index_data :
            index_data['type'] = 'album'
        
        return index_data

    ##########################################################
    def is_music(self, file : Path) -> bool :
        return (file.is_file() & (file.suffix in ('.wav', '.mp3', '.flac')))

    ##########################################################
    def output_data(self) -> None :

        music : List[Track] = []
        albums : List[Album] = []
        print("artists :", file=self.output)
        for a in self.artists :
            prefix = '  - '
            self.output.write(f"{prefix}id : {a.id}\n")
            prefix = '    '
            self.output.write(f"{prefix}name : {a.name}\n")
            self.output.write(f"{prefix}sort_name : {a.sort_name}\n")
            if len(a.assoc) > 0 :
                prefix = '     - '
                self.output.write(f"{prefix}music :\n")
                prefix = '       - '
                for m in a.assoc :
                    self.output.write(f"{prefix} {{ id : {m.id}, kind : {m.kind} }}\n")
                    if m.kind == 'Track' : 
                        music.append(cast(Track, m))
                    elif m.kind == 'Album' :
                        albums.append(cast(Album, m))
                    else :
                        raise Exception(f"Unknown OwnableMusic kind '{m.kind}'")

        if len(music) > 0 :
            self.output.write("tracks :\n")
            seenMusic : Set[str] = set()
            for m in music :
                if m.id in seenMusic :
                    continue
                prefix = '  - '
                self.output.write(f"{prefix}id : {m.id}\n")
                prefix = '    '
                self.output.write(f"{prefix}name : {m.name}\n")
                self.output.write(f"{prefix}sort_name : {m.sort_name}\n")
                self.output.write(f"{prefix}file :\n")
                prefix = prefix + '  '
                self.output.write(f"{prefix}id : {m.file.id}\n")
                self.output.write(f"{prefix}path : {m.file.path}\n")
                self.output.write(f"{prefix}format : {m.file.format}\n")
                seenMusic.add(m.id)

        if len(albums) > 0 :
            self.output.write("albums : \n")
            seenAlbums : Set[str] = set()
            for a in albums :
                if a.id in seenAlbums :
                    continue
                seenAlbums.add(a.id)
                prefix = '  - '
                self.output.write(f"{prefix}id : {a.id}\n")
                prefix = '    '
                self.output.write(f"{prefix}name : {a.name}\n")
                self.output.write(f"{prefix}sort_name : {a.sort_name}\n")
                self.output.write(f"{prefix}tracks : \n")
                for t in a.tracks :
                    prefix = '    - '
                    self.output.write(f"{prefix}name : {t.name}\n")
                    prefix = '      '
                    self.output.write(f"{prefix}pos : {t.pos}\n")
                    self.output.write(f"{prefix}file :\n")
                    prefix = prefix + '  '
                    self.output.write(f"{prefix}id : {t.file.id}\n")
                    self.output.write(f"{prefix}path : {t.file.path}\n")
                    self.output.write(f"{prefix}format : {t.file.format}\n")



##########################################################
def getargs() -> Namespace :
    parser = ArgumentParser()

    parser.add_argument('--dir', default='/mnt/music/Bandcamp')
    parser.add_argument('--out', default='-')

    return parser.parse_args()

##########################################################
if __name__ == '__main__' :

    args = getargs()
    need_to_close = False
    if args.out == '-' :
        output = sys.stdout
    else :
        output = open(args.out, 'w')
        need_to_close = True

    obj = Curate(directory=args.dir, output=output)
    retval = obj.launch()

    if need_to_close :
        output.close()


    exit(retval)
