from dataclasses import dataclass, field
from nanoid import generate
from pathlib import Path
from typing import Any, Dict, List

def get_id() -> str :
    """Generate a random ID string
    """
    return generate("23456789abcdefghijkmnpqrstuvwxyzABCDEFGHIJKMNPQRSTUVWXYZ",20)

@dataclass
class MusicFile :
    path   : Path
    format : str # currently one of 'wav' or 'mp3'
    digest : str # sha256 hash of the file
    tags   : Dict[str, Any] | None = None

@dataclass
class Track :
    file : MusicFile
    name : str
    sort_name : str | None = None
    id : str = field(default_factory=get_id)

    def __post_init__(self) :
        if self.sort_name is None :
            self.sort_name = self.name

@dataclass
class Album :
    name : str
    sort_name : str | None = None
    id : str = field(default_factory=get_id)
    cover : str | None = None

    def __post_init__(self) :
        if self.sort_name is None :
            self.sort_name = self.name

    def add_track(self, track : Track, pos : int) :
        albumTrackList.append(AlbumTrack(self.id, track.id, pos))
        trackList.append(track)

@dataclass
class AlbumTrack :
    album : str # id
    track : str # id
    pos  : int

@dataclass
class Artist :
    name : str
    sort_name : str | None = None
    id : str = field(default_factory=get_id)

    def __post_init__(self) :
        if self.sort_name is None :
            self.sort_name = self.name


    def add_track(self, track : Track) :
        artistAssociationList.append(ArtistAssociation(self.id, track.id, 'Track'))
        trackList.append(track)

    def add_album(self, album : Album) :
        artistAssociationList.append(ArtistAssociation(self.id, album.id, 'Album'))
        albumList.append(album)

@dataclass
class ArtistAssociation :
    artist : str # id
    music  : str # id ( could be album or track )
    kind   : str

class ArtistManager :
    def __init__(self) :
        self.byid : Dict[str, Artist]  = {} # by id
        self.names : Dict[str, Artist] = {} # by name

        # This id will not be generated by get_id()
        # If the alphabet changes, may need to tweak this.
        self._unknown_id =  '--unknown--'
        self._unknown = Artist(self._unknown_id, self._unknown_id, self._unknown_id)
        self.byid[self._unknown_id] = self._unknown
        self.names[self._unknown_id] = self._unknown

    def unknown(self) -> Artist :
        """Return the record of the `unknown` entity"""
        return self._unknown

    def add_artist(self, name : str, sort_name : str | None = None) -> Artist :
        """Add an artist of the given name and sort_name.
        If the artist name already exists, simply return the record
        params :
            name : artist's name (required)
            sort_name : string to use to sort. If not given, use the @name

        returns :
            Record of the artist.
        """
        sort_name = sort_name if sort_name else name
        if name in self.names :
            return self.names[name]

        artist = Artist(name, sort_name)
        self.byid[artist.id] = artist
        self.names[name] = artist

        return artist


    def __iter__(self) :
        return iter(sorted(self.byid.values(), key=lambda v: v.sort_name)) # type: ignore

#############################################
# Global lists
#############################################
trackList : List[Track] = []
albumList : List[Album] = []
albumTrackList : List[AlbumTrack] = []
artistAssociationList : List[ArtistAssociation] = []

__ALL__ = [
    trackList, albumList, albumTrackList, artistAssociationList, 
    ArtistManager, MusicFile, Track, Album, AlbumTrack, Artist, ArtistAssociation
]